server:
  port: 8080
  servlet:
    context-path: /security
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: bestuser
    password: bestuser

## MySQL properties
#driver=com.mysql.cj.jdbc.Driver
#url=jdbc:mysql://localhost:3306/pp_db?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
#username=bestuser
#password=bestuser
#
## Hibernate properties
#hibernate.show_sql=true
#hibernate.hbm2ddl.auto=update
#hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
